# Generated by Django 4.1.13 on 2024-04-03 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KneePatients',
            fields=[
                ('PatientId', models.AutoField(primary_key=True, serialize=False)),
                ('PatientName', models.CharField(max_length=500)),
                ('Age', models.IntegerField()),
                ('Gender', models.CharField(max_length=500)),
                ('XRayImageFileName', models.CharField(max_length=500)),
                ('SegmentedImageFileName', models.CharField(max_length=500)),
                ('PreviousInjuries', models.BooleanField(default=False)),
                ('Genetics', models.BooleanField(default=False)),
                ('Height', models.FloatField()),
                ('Weight', models.FloatField()),
            ],
        ),
    ]
