# Generated by Django 4.1.13 on 2024-04-03 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClassifyKOAImagesApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kneepatients',
            name='Age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kneepatients',
            name='Gender',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='kneepatients',
            name='Genetics',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='kneepatients',
            name='Height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kneepatients',
            name='PatientName',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='kneepatients',
            name='PreviousInjuries',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='kneepatients',
            name='SegmentedImageFileName',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='kneepatients',
            name='Weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kneepatients',
            name='XRayImageFileName',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
