# Generated by Django 4.1.13 on 2024-04-03 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClassifyKOAImagesApp', '0002_alter_kneepatients_age_alter_kneepatients_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kneepatients',
            name='OutputClass',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
